---
title: Le projet Onyxia
subtitle: |
  **[Comment tirer parti\
  des technologies cloud\
  sans se faire enfermer ?]{.orange}**
author: |
  Romain Lesur
date: 2024-06-14
slide-number: true
footer: |
  **Rencontres R 2024**
# uncomment for French presentations:
lang: fr
# for blind readers:
slide-tone: false
# for @olevitt:
chalkboard: # press the B key to toggle chalkboard
  theme: whiteboard
# uncomment to use the multiplex mode:
#multiplex: true
format:
  # pick the light mode (onyxia-revealjs) or the dark mode (onyxia-dark-revealjs)
  #onyxia-revealjs:
  onyxia-dark-revealjs:
    output-file: index.html
# visual editor configuration:
editor:
  render-on-save: true
---

## Qui suis-je ?

- Responsable du SSP Lab, le Lab de Data Science à l'Insee
- (ancien) contributeur à la communauté R

## Les besoins de traitement de données à l'Insee

- Un millier de personnes touchant la donnée avec des langages de programmation (R, python...)
- Depuis plus de 15 ans, un écosystème en très forte évolution
- Développement de la _data science_ : des besoins plus vastes et hétérogènes
- L'infrastructure : frein ou facilitateur ?

## L'évolution de l'informatique pour le traitement de données

A l'Insee :

- 1950s-1990s : ordinateurs centraux (mainframes)
- 1990s-2010s : ordinateurs personnels (PC)
- 2010s-... : serveurs mutualisés/bureau à distance
- 2023 : technologies cloud

## Les enjeux

- Puissance de calcul
  * Les PC ont leurs limites
- Besoin d'une grande flexibilité (outils, langages, packages...) mais aussi de reproductibilité
- Sécurité des données/contrôle d'accès
  * Le PC est un environnement à proscrire
- Le passage en production
  * Déploiement d'applications/API
  * MLOps (orchestration/monitoring)
- Risque d'enfermement propriétaire

## Les opportunités offertes par les technologies cloud

- Conteneurs (Docker)
  * Flexibles
  * Portables 
  * Facilitent la reproductibilité
- Orchestrateur de conteneurs (Kubernetes)
  * Passage à l'échelle
  * Facilite le passage en production
- Stockage objet (S3)
  * Facilite la gestion des données
  * Facilite les usages de data science

## L'ADN du projet Onyxia

- Une plateforme orientée data science facilitant le passage en production
- 100% open source (licence MIT)
- Aucun enfermement propriétaire
- 100% cloud native
- Déployable n'importe où (cloud, on premises...)

## Onyia en action

{{< video https://www.youtube.com/embed/FvpNfVrxBFM?si=Ekc0-3IXyv2imoVv&autoplay=1 width="100%" height="85%" >}}

## Des pré-requis

- Kubernetes
- S3

## SSP Cloud

Un datalab en ligne <https://datalab.sspcloud.fr> pour

- prototyper
- se former
- exclusivement sur des **données ouvertes**
- accessible aux acteurs de l'ESR
- un service en _best effort_
- un [catalogue de formations](https://www.sspcloud.fr/formation) à la _data science_

## La communauté Onyxia

[onyxia.sh](https://onyxia.sh)

- Un [slack](https://join.slack.com/t/3innovation/shared_invite/zt-1hnzukjcn-6biCSmVy4qvyDGwbNI~sWg)
- _Community meetings_ chaque dernier vendredi du mois
- Retrouvez les acteurs ayant adopté Onyxia : Insee, Statistics Norway, Mercator Ocean International, GENES...
